

image_analysis_task:
  description: >
    Analyze the provided satellite image and event details to determine wildfire spread, smoke density, and potential impact.
    Emergency Event Details-
    {event_details}
  expected_output: >
    A detailed report containing the following sections:
    1. Description of the wildfire event (location, intensity, area affected).
    2. Analysis of smoke density and movement patterns.
    3. Estimation of wildfire spread based on visual cues.
    4. Environmental impact assessment (flora, fauna, nearby settlements).
    5. Recommendations for further monitoring or intervention.
  agent: image_analysis_agent
