# image_generation_task:
#   description: >
#     Ensure the image captures the essence of the scene and meets the requirements specified in terms of size and quality.
#   expected_output: >
#     An image file of size 1024x1024 pixels that visualizes the concept described in the prompt.
#   agent: image_generator_agent

monitoring_task:
  description: >
    Use the wildfire monitoring tool to fetch events from EONET source in the next 20 days and extract at most one wildfire spread event in USA from the list of events. Limit to only one event.
  expected_output: >
    JSON of the wildfire event. Expected output:
    {
      "id": "EONET_12019",
      "title": "BRIDGE BAER IMPLEMENTATION Wildfire, Los Angeles, California",
      "description": null,
      "link": "https://eonet.gsfc.nasa.gov/api/v3/events/EONET_12019",
      "closed": null,
      "categories": [
        {
          "id": "wildfires",
          "title": "Wildfires"
        }
      ],
      "sources": [
        {
          "id": "IRWIN",
          "url": "https://irwin.doi.gov/observer/"
        }
      ],
      "geometry": [
        {
          "magnitudeValue": 820.0,
          "magnitudeUnit": "acres",
          "date": "2024-11-18T15:27:00Z",
          "type": "Point",
          "coordinates": [
            -117.758,
            34.2305
          ]
        }
      ]
    }
    
  agent: monitoring_agent