

safe_zones_task:
  description: >
    Locate safe zones (campgrounds, open parking lots, stadiums, parks, locality) outside of the potential spread radius of the wildfire.
  expected_output: >
    JSON of safe zones that fall outside the potential spread radius of the wildfire. Example output format:
    
  agent: safe_zones_agent

## Try to use the places identified in the places search task
resource_deployment_task:
  description: >
    Allocate firefighting resources (like fire engines, water dropping helicopters, etc.) and personnel (first responders, medicos, etc.) based on the real-time wildfire spread data to ensure optimal deployment to high-risk areas. High risk areas include schools, residential places, gas stations and hospitals. Assume you have certain resources available. 
  expected_output: >
    # High risk areas identified
    [Areas and their coordinates]
    # Resource allocation plan
    [detailed deployment schedules and distribution of firefighting equipment to high risk areas]
    
  agent: resource_deployment_agent

# communication_task:
#   description: >
#     Inform the public about evacuation orders, safety measures, and wildfire updates using multiple communication channels.
#   expected_output: >
#     Public announcements including evacuation orders, safety guidelines, and updates on wildfire containment status, formatted for dissemination through various media.
#   agent: communication_agent

route_planning_task:
  description: >
    Given a list of high risk areas and safe zones, efficiently plan the routes from each high risk area to a safe zone.
  expected_output: >
    JSON collection of optimized routes for vehicles to navigate safely from all high risk zones to safe zones. Example output:
    
  agent: route_planning_agent

