image_generation_task:
  description: >
    Ensure the image captures the essence of the scene and meets the requirements specified in terms of size and quality.
  expected_output: >
    An image file of size 1024x1024 pixels that visualizes the concept described in the prompt.
  agent: image_generator_agent

monitoring_task:
  description: >
    Continuously analyze real-time data from satellite images, weather conditions, and ground sensors to map the current wildfire spread and identify affected areas.
  expected_output: >
    Up-to-date wildfire spread map highlighting affected areas and projected spread direction.
  agent: monitoring_agent

evacuation_task:
  description: >
    Develop detailed evacuation plans for communities in the wildfire's projected path, ensuring safety and efficiency in moving residents to designated shelters.
  expected_output: >
    Comprehensive evacuation routes, shelter locations, and step-by-step evacuation procedures.
  agent: evacuation_agent

resource_task:
  description: >
    Allocate firefighting resources and personnel based on the real-time wildfire spread data to ensure optimal deployment to high-risk areas.
  expected_output: >
    Resource allocation plan detailing deployment schedules and distribution of firefighting equipment to priority zones.
  agent: resource_agent

communication_task:
  description: >
    Inform the public about evacuation orders, safety measures, and wildfire updates using multiple communication channels.
  expected_output: >
    Public announcements including evacuation orders, safety guidelines, and updates on wildfire containment status, formatted for dissemination through various media.
  agent: communication_agent

