# image_generation_task:
#   description: >
#     Ensure the image captures the essence of the scene and meets the requirements specified in terms of size and quality.
#   expected_output: >
#     An image file of size 1024x1024 pixels that visualizes the concept described in the prompt.
#   agent: image_generator_agent


impact_analysis_task:
  description: >
    Analyze wildfire spread using Earth Observatory Natural Event tracker (EONET) data, places (towns and cities) near to the wildfire event, weather data and drone images (if available) and determine the impact of the event. Get a human input before before proceeding further.
  expected_output: >
    Detailed report for the analysis containing the following sections:
    1. Event Details
    2. Impact of weather on the event
    3. Image analysis
    4. Potential spread path
    [with radius of the spread]
    5. Places impacted  
    6. Analysis of the entire event 
    
  agent: impact_analysis_agent

monitoring_task:
  description: >
    Use the wildfire monitoring tool to Fetch events from EONET source in the next 20 days and extract the immediate next wildfire spread event.
  expected_output: >
    JSON of the next wildfire event. Limit to one event.
    
  agent: monitoring_agent

places_search_task:
  description: >
    Calculate the potential spread radius of the wildfire, taking into account weather information and event details. Use the Google Places Search API to identify localities within that radius.
  expected_output: >
    A list of populated areas including cities and towns that fall within the potential spread radius of the wildfire, formatted for use in evacuation and resource allocation planning.
  agent: places_search_agent

safe_zones_identifier_task:
  description: >
    Analyze the spread of the wildfire, along with high risk areas, to identify safe zones outside of the potential spread radius.
  expected_output: >
    A list of safe zones, including their latitude, longitude and other attributes, to be used for shelter and safe evacuation planning.
  agent: safe_zones_identifier_agent

## Try to use the places identified in the places search task
resource_deployment_task:
  description: >
    Allocate firefighting resources (like fire engines, water dropping helicopters, etc.) and personnel (first responders, medicos, etc.) based on the real-time wildfire spread data to ensure optimal deployment to high-risk areas. High risk areas include schools, residential places, gas stations and hospitals. Assume you have certain resources available. 
  expected_output: >
    # High risk areas identified
    [Areas and their coordinates]
    # Resource allocation plan
    [detailed deployment schedules and distribution of firefighting equipment to high risk areas]
  agent: resource_deployment_agent

# communication_task:
#   description: >
#     Inform the public about evacuation orders, safety measures, and wildfire updates using multiple communication channels.
#   expected_output: >
#     Public announcements including evacuation orders, safety guidelines, and updates on wildfire containment status, formatted for dissemination through various media.
#   agent: communication_agent

evac_route_planning_task:
  description: >
    Plan optimal routes for civilian vehicles from high risk zones to safe zones, considering current wildfire spread and road closures.
  expected_output: >
    JSON collection of optimized google map routes for vehicles to navigate safely from high risk zones to safe zones, avoiding high risk areas.
  agent: evac_route_planning_agent

weather_task:
  description: >
    Fetches real-time weather updates, including current conditions, 3-hourly forecasts for next 4 intervals, and weather alerts for the monitored areas.
  expected_output: >
    Weather data containing the current weather, hourly weather forecast, and any active weather alerts, formatted to assist in decision-making during emergency response.
  agent: weather_agent